# Limpieza dataset INEGI

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import os

In [41]:
archivo = "C:\\Users\\Dell Latitude\\Documents\\GitHub\\ESCOM_advanced-databases\\data\\conjunto_de_datos_iter_00CSV20.csv"
data = pd.read_csv(archivo)
data

C:\Users\Dell Latitude\AppData\Local\Temp\ipykernel_12340\995141599.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(archivo)

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,...,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,...,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,...,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,...,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,...,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,...,732,205,212,48,41,39,62,530,20,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195657,32,Zacatecas,58,Santa María de la Paz,37,Mesa Grande,"103°24'52.925"" W","21°33'12.375"" N",1944.0,165,...,24,9,13,0,0,3,9,38,1,1
195658,32,Zacatecas,58,Santa María de la Paz,39,San Isidro,"103°20'14.164"" W","21°29'11.130"" N",2031.0,1,...,*,*,*,*,*,*,*,*,*,1
195659,32,Zacatecas,58,Santa María de la Paz,41,San Miguel Tepetitlán,"103°20'09.356"" W","21°30'15.168"" N",1977.0,97,...,21,12,21,1,1,1,10,19,0,1
195660,32,Zacatecas,58,Santa María de la Paz,42,San Rafael,"103°22'20.134"" W","21°31'39.341"" N",2042.0,3,...,*,*,*,*,*,*,*,*,*,1
195661,32,Zacatecas,58,Santa María de la Paz,9998,Localidades de una vivienda,NaN,NaN,NaN,32,...,7,2,6,1,1,1,2,7,1,*

In [42]:
data.describe()

,ENTIDAD,MUN,LOC,POBTOT,VIVTOT,TVIVHAB
count,195662.000000,195662.000000,195662.000000,1.956620e+05,1.956620e+05,1.956620e+05
mean,16.806743,59.699400,623.572221,2.582252e+03,9.000329e+02,7.218171e+02
std,8.940159,81.370934,1502.609425,2.931486e+05,1.019782e+05,8.195072e+04
min,0.000000,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000,12.000000,45.000000,4.000000e+00,2.000000e+00,1.000000e+00
50%,16.000000,33.000000,162.000000,1.600000e+01,7.000000e+00,4.000000e+00
75%,25.000000,73.000000,531.000000,1.470000e+02,5.400000e+01,3.800000e+01
max,32.000000,570.000000,9999.000000,1.260140e+08,4.390344e+07,3.523346e+07

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195662 entries, 0 to 195661
Columns: 286 entries, ENTIDAD to TAMLOC
dtypes: int64(6), object(280)
memory usage: 426.9+ MB

In [44]:
data.columns

Index(['ENTIDAD', 'NOM_ENT', 'MUN', 'NOM_MUN', 'LOC', 'NOM_LOC', 'LONGITUD',
       'LATITUD', 'ALTITUD', 'POBTOT',
       ...
       'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI', 'VPH_CVJ',
       'VPH_SINRTV', 'VPH_SINLTC', 'VPH_SINCINT', 'VPH_SINTIC', 'TAMLOC'],
      dtype='object', length=286)

In [45]:
data.columns[:12]

Index(['ENTIDAD', 'NOM_ENT', 'MUN', 'NOM_MUN', 'LOC', 'NOM_LOC', 'LONGITUD',
       'LATITUD', 'ALTITUD', 'POBTOT', 'POBFEM', 'POBMAS'],
      dtype='object')

In [46]:
data_sliced = data.iloc[:, :12]

In [32]:
data_sliced

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,64540634,61473390
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,96869,153485
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,61324,85801
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,728924,696683
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,1510,2187
...,...,...,...,...,...,...,...,...,...,...,...,...
195657,32,Zacatecas,58,Santa María de la Paz,37,Mesa Grande,"103°24'52.925"" W","21°33'12.375"" N",1944.0,165,88,77
195658,32,Zacatecas,58,Santa María de la Paz,39,San Isidro,"103°20'14.164"" W","21°29'11.130"" N",2031.0,1,*,*
195659,32,Zacatecas,58,Santa María de la Paz,41,San Miguel Tepetitlán,"103°20'09.356"" W","21°30'15.168"" N",1977.0,97,50,47
195660,32,Zacatecas,58,Santa María de la Paz,42,San Rafael,"103°22'20.134"" W","21°31'39.341"" N",2042.0,3,*,*
195661,32,Zacatecas,58,Santa María de la Paz,9998,Localidades de una vivienda,NaN,NaN,NaN,32,11,21

In [47]:
import csv

def csv_a_sql(nombre_archivo_csv, nombre_archivo_sql, nombre_tabla):
    """
    Convierte un archivo CSV a un script SQL para crear una tabla e insertar datos.

    Args:
        nombre_archivo_csv: La ruta al archivo CSV de entrada.
        nombre_archivo_sql: La ruta al archivo SQL de salida.
        nombre_tabla: El nombre de la tabla SQL que se creará.
    """

    with open(nombre_archivo_csv, 'r', encoding='utf-8') as archivo_csv, open(nombre_archivo_sql, 'w', encoding='utf-8') as archivo_sql:
        lector_csv = csv.reader(archivo_csv)
        
        # Obtener la primera fila para los nombres de las columnas
        encabezado = next(lector_csv)

        # Crear la sentencia CREATE TABLE
        archivo_sql.write(f"CREATE TABLE {nombre_tabla} (\n")
        for nombre_columna in encabezado:
            # Limpiar y formatear el nombre de la columna para SQL
            nombre_columna = nombre_columna.replace(" ", "_").lower()  # Ejemplo: "Nombre Cliente" -> "nombre_cliente"
            archivo_sql.write(f"    {nombre_columna} TEXT,\n")  # Asume tipo TEXT, puedes ajustarlo
        archivo_sql.write(");\n\n")

        # Crear las sentencias INSERT INTO
        for fila in lector_csv:
            archivo_sql.write(f"INSERT INTO {nombre_tabla} (")
            archivo_sql.write(", ".join(f'"{col.replace(" ", "_").lower()}"' for col in encabezado))  # Columnas
            archivo_sql.write(") VALUES (")
            archivo_sql.write(", ".join(f"'{valor}'" for valor in fila))  # Valores
            archivo_sql.write(");\n")

In [48]:
for column in data_sliced.columns:
    print("Valores nulos en ", column, '\t\t',data_sliced[column].isna().sum())

Valores nulos en  ENTIDAD 		 0
Valores nulos en  NOM_ENT 		 0
Valores nulos en  MUN 		 0
Valores nulos en  NOM_MUN 		 0
Valores nulos en  LOC 		 0
Valores nulos en  NOM_LOC 		 0
Valores nulos en  LONGITUD 		 6230
Valores nulos en  LATITUD 		 6230
Valores nulos en  ALTITUD 		 6230
Valores nulos en  POBTOT 		 0
Valores nulos en  POBFEM 		 0
Valores nulos en  POBMAS 		 0

In [33]:
data_sliced.shape

(195662, 12)

In [49]:
null_counts = data_sliced.apply(lambda col: (col == '*').sum())

print("Valores nulos por columna:")
print(null_counts)

Valores nulos por columna:
ENTIDAD         0
NOM_ENT         0
MUN             0
NOM_MUN         0
LOC             0
NOM_LOC         0
LONGITUD        0
LATITUD         0
ALTITUD         0
POBTOT          0
POBFEM      82011
POBMAS      82011
dtype: int64

In [50]:
# Reemplazar '*' con NaN
data_withNull = data_sliced.replace('*', pd.NA)

In [51]:
data_withNull.shape

(195662, 12)

In [52]:
for column in data_withNull.columns:
    print("Valores nulos en ", column, '\t\t',data_withNull[column].isna().sum())

Valores nulos en  ENTIDAD 		 0
Valores nulos en  NOM_ENT 		 0
Valores nulos en  MUN 		 0
Valores nulos en  NOM_MUN 		 0
Valores nulos en  LOC 		 0
Valores nulos en  NOM_LOC 		 0
Valores nulos en  LONGITUD 		 6230
Valores nulos en  LATITUD 		 6230
Valores nulos en  ALTITUD 		 6230
Valores nulos en  POBTOT 		 0
Valores nulos en  POBFEM 		 82011
Valores nulos en  POBMAS 		 82011

In [53]:
data_sliced_clean = data_withNull.copy()

In [54]:
data_sliced_clean.shape

(195662, 12)

In [55]:
null_counts = data_sliced_clean.isna().sum()

print("Valores nulos por columna:")
print(null_counts)

Valores nulos por columna:
ENTIDAD         0
NOM_ENT         0
MUN             0
NOM_MUN         0
LOC             0
NOM_LOC         0
LONGITUD     6230
LATITUD      6230
ALTITUD      6230
POBTOT          0
POBFEM      82011
POBMAS      82011
dtype: int64

In [56]:
# Eliminar filas con valores nulos
data_sliced_clean.dropna(inplace=True)

# Reiniciar los índices después de eliminar filas
data_sliced_clean.reset_index(drop=True, inplace=True)

data_sliced_clean

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,POBFEM,POBMAS
0,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,"102°17'45.768"" W","21°52'47.362"" N",1878.0,863893,444725,419168
1,1,Aguascalientes,1,Aguascalientes,96,Agua Azul,"102°21'25.639"" W","21°53'01.522"" N",1861.0,41,17,24
2,1,Aguascalientes,1,Aguascalientes,106,Arellano,"102°16'26.238"" W","21°48'06.384"" N",1892.0,1169,556,613
3,1,Aguascalientes,1,Aguascalientes,112,Bajío los Vázquez,"102°07'29.341"" W","21°44'50.978"" N",1971.0,41,21,20
4,1,Aguascalientes,1,Aguascalientes,120,Buenavista de Peñuelas,"102°17'35.503"" W","21°43'08.930"" N",1871.0,1054,512,542
...,...,...,...,...,...,...,...,...,...,...,...,...
108322,32,Zacatecas,58,Santa María de la Paz,30,Las Tablas,"103°15'41.651"" W","21°27'38.476"" N",2464.0,34,20,14
108323,32,Zacatecas,58,Santa María de la Paz,33,Los Horcones,"103°16'01.480"" W","21°29'55.089"" N",2152.0,12,4,8
108324,32,Zacatecas,58,Santa María de la Paz,35,Los Trigos (Mesa de los Trigos),"103°14'27.792"" W","21°29'51.355"" N",2499.0,89,43,46
108325,32,Zacatecas,58,Santa María de la Paz,37,Mesa Grande,"103°24'52.925"" W","21°33'12.375"" N",1944.0,165,88,77
108326,32,Zacatecas,58,Santa María de la Paz,41,San Miguel Tepetitlán,"103°20'09.356"" W","21°30'15.168"" N",1977.0,97,50,47

In [57]:
null_counts = data_sliced_clean.isna().sum()

print("Valores nulos por columna:")
print(null_counts)

Valores nulos por columna:
ENTIDAD     0
NOM_ENT     0
MUN         0
NOM_MUN     0
LOC         0
NOM_LOC     0
LONGITUD    0
LATITUD     0
ALTITUD     0
POBTOT      0
POBFEM      0
POBMAS      0
dtype: int64

In [59]:
data_sliced_clean.shape, data_withNull.shape

((108327, 12), (195662, 12))

In [60]:
data_sliced_clean.to_csv("inegi_clean.csv", index=False)
data_withNull.to_csv("inegi_nulls.csv", index=False)

In [61]:
csv_a_sql("inegi_clean.csv", "inegi_clean_mysql.sql", "inegi_clean")
csv_a_sql("inegi_nulls.csv", "inegi_nulls_mysql.sql", "inegi_nulls")